version: '3'
services:
  # Backend API
  nestjs-app:
    container_name: audit-logger-app
    build:
      context: .
      dockerfile: Dockerfile
      # Only will build development stage from our dockerfile
      target: development
    env_file:
      - .env
    # Run a command against the development stage of the image
    command: yarn run start:dev
    ports:
      - 3000:3000
    depends_on:
      - redis
      - postgres-db
    restart: unless-stopped
  #   networks:
  #     - audit-logger-app-network
  #   volumes:
  #     - .:/usr/src/app

  # Redis
  redis:
    container_name: redis-con
    image: redis
    ports:
      - 6388:6379
    # volumes:
    #   - redis:/data
    # networks:
    #   - audit-logger-app-network

  # Postgres
  postgres-db:
    container_name: postgres16-con
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - '5434:5432'
    restart: always
    # networks:
    #   - audit-logger-app-network
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      # - docker-nest-postgres:/var/lib/postgresql/data
      # Above volume got issue with missing postgres config file that cause all environment config not working,
      # I think cause from define wrong volume directory
# volumes:
#   redis:
#     driver: local
#   docker-nest-postgres:

# networks:
#   audit-logger-app-network:
#     driver: bridge
